# https://redwoodjs.com/docs/app-configuration-redwood-toml
[web]
  title = "d11z.me"
  port = 8910
  apiUrl = "/.netlify/functions"
  includeEnvironmentVariables = [] # any ENV vars that should be available to the web side, see https://redwoodjs.com/docs/environment-variables#web
[api]
  port = 8911
[browser]
  open = false
